# Development version with simplified configuration
version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "80:80"
    depends_on:
      - backend
      - worker
    networks:
      - dev-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/fileprocessing
    depends_on:
      - database
    volumes:
      - ./backend:/app
    networks:
      - dev-network

  worker:
    build: ./worker
    ports:
      - "8001:8001"
    volumes:
      - ./worker:/app
    networks:
      - dev-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fileprocessing
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  dev_postgres_data: