global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend-api'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8001']
