"""Remove votes_count from videos table

Revision ID: remove_votes_count
Revises: 7ea02b3bb4ea
Create Date: 2025-10-14 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_votes_count'
down_revision = '7ea02b3bb4ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'votes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('votes_count', sa.INTEGER(), nullable=False, server_default='0'))
    # ### end Alembic commands ###
