version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "80:80"
    depends_on:
      - backend
      - worker
    networks:
      - app-network
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TEST_MODE=false
      - DATABASE_URL=postgresql://user:password@database:5432/fileprocessing
      - REDIS_URL=redis://redis:6379/0
      - MINIO_URL=http://minio:9000
      - UPLOAD_DIR=/app/uploads
      - BASE_PATH=http://localhost:80/api/videos
    volumes:
      - video_storage:/app/uploads  # Volumen compartido con worker

    depends_on:
      - database
      - redis
      - minio

    networks:
      - app-network
    restart: unless-stopped

  # Task Processor Worker (Celery + FastAPI Health Checks)
  worker:
    build: ./worker
    ports:
      - "8001:8001"  # Health API
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/fileprocessing
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
      - BASE_PATH=http://localhost:80/api/videos
      - CELERY_CONCURRENCY=4
      - CELERY_MAX_RETRIES=3
      - LOG_LEVEL=INFO
    volumes:
      - video_storage:/app/uploads  # Volumen compartido con backend
    depends_on:
      - database
      - redis
    networks:
      - app-network
    restart: unless-stopped
    command: >
      sh -c "python main.py &
             celery -A celery_app worker --loglevel=info --concurrency=4 --queues=video_processing,dlq"
  
  # Flower - Monitoreo de Celery
  flower:
    image: mher/flower:2.0
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    depends_on:
      - redis
      - worker
    networks:
      - app-network
    restart: unless-stopped
    command: celery --broker=redis://redis:6379/0 flower --port=5555

  # PostgreSQL Database
  database:
    build: ./database
    environment:
      - POSTGRES_DB=fileprocessing
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:
  video_storage:
    name: video_storage
