name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  # Etapa 1: Ejecución de pruebas unitarias
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install backend dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
        
        # Verificar que las dependencias se instalaron correctamente
        echo "=== Backend Dependencies Check ==="
        pip list | grep -E "(fastapi|pytest|sqlalchemy|psycopg2)"
        echo "=================================="

    - name: Install worker dependencies
      run: |
        cd worker
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests (SQLite)
      run: |
        cd backend
        export DATABASE_URL="sqlite:///./test.db"
        export REDIS_URL="redis://localhost:6379/0"
        export TEST_MODE=true
        export UPLOAD_DIR="/tmp/test_uploads"
        mkdir -p /tmp/test_uploads/original /tmp/test_uploads/processed
        
        # Crear las tablas de la base de datos
        python3 -c "
        from app.infrastructure.database.database import engine, Base
        from app.infrastructure.database import models
        Base.metadata.create_all(bind=engine)
        print('✅ Database tables created successfully')
        "
        
        # Ejecutar las pruebas usando app_test_main (que ya tiene la configuración correcta)
        pytest tests/ -v --cov=app --cov-report=xml --cov-report=html

    - name: Run worker tests (SQLite)
      run: |
        cd worker
        export DATABASE_URL="sqlite:///./test.db"
        export REDIS_URL="redis://localhost:6379/0"
        export UPLOAD_DIR="/tmp/test_uploads"
        pytest tests/ -v --cov=tasks --cov-report=xml --cov-report=html

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/coverage.xml,./worker/coverage.xml
        flags: unittests
        name: codecov-umbrella

  # Etapa 2: Construcción automática de la aplicación
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: false
        tags: misw4204-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build worker image
      uses: docker/build-push-action@v5
      with:
        context: ./worker
        push: false
        tags: misw4204-worker:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build API Gateway image
      uses: docker/build-push-action@v5
      with:
        context: ./api-gateway
        push: false
        tags: misw4204-api-gateway:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build database image
      uses: docker/build-push-action@v5
      with:
        context: ./database
        push: false
        tags: misw4204-database:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker Compose
      run: |
        # Verificar que docker compose puede construir todos los servicios
        docker compose -f docker-compose.yml config
        echo "Docker Compose configuration is valid"

  # Etapa 3: Validación de calidad del código con SonarCloud
  sonarcloud:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
        cd ../worker
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        # Backend tests with coverage
        cd backend
        export DATABASE_URL="sqlite:///./test.db"
        export REDIS_URL="redis://localhost:6379/0"
        export TEST_MODE=true
        export UPLOAD_DIR="/tmp/test_uploads"
        mkdir -p /tmp/test_uploads/original /tmp/test_uploads/processed
        pytest tests/ --cov=app --cov-report=xml --cov-report=term

        # Worker tests with coverage
        cd ../worker
        export DATABASE_URL="sqlite:///./test.db"
        export REDIS_URL="redis://localhost:6379/0"
        export UPLOAD_DIR="/tmp/test_uploads"
        pytest tests/ --cov=tasks --cov-report=xml --cov-report=term

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Job de notificación (opcional)
  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test, build, sonarcloud]
    if: always()
    
    steps:
    - name: Notify Success
      if: ${{ needs.test.result == 'success' && needs.build.result == 'success' && needs.sonarcloud.result == 'success' }}
      run: |
        echo "✅ All CI/CD stages completed successfully!"
        echo "✅ Unit tests passed"
        echo "✅ Application built successfully"
        echo "✅ Code quality analysis passed"

    - name: Notify Failure
      if: ${{ needs.test.result == 'failure' || needs.build.result == 'failure' || needs.sonarcloud.result == 'failure' }}
      run: |
        echo "❌ CI/CD pipeline failed!"
        echo "Test result: ${{ needs.test.result }}"
        echo "Build result: ${{ needs.build.result }}"
        echo "SonarCloud result: ${{ needs.sonarcloud.result }}"
        exit 1
